### ISSUE TITLE
Failure after following README instructions

### ISSUE THREAD

**Issue by DustinCampbell** [Ref12/Codex#101] opened 2018-04-18 16:21 UTC
After following the instructions in the readme, I get an error that I'm not at all sure how to debug. Any tips or ideas?

```
Invalid NEST response built from a unsuccessful low level call on PUT: /msbuildworkspacetester.180418.161234?pretty=true
# Audit trail of this API call:
 - [1] BadResponse: Node: http://localhost:9200/ Took: 00:00:06.6591472
# ServerError: ServerError: 400Type: mapper_parsing_exception Reason: "Failed to parse mapping [projects]: No handler for type [string] declared on field [projectId]" CausedBy: "Type: mapper_parsing_exception Reason: "No handler for type [string] declared on field [projectId]""
# OriginalException: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Elasticsearch.Net.HttpConnection.<RequestAsync>d__14`1.MoveNext()
# Request:
{
  "settings": {
    "analysis": {
      "analyzer": {
        "partial_name": {
          "tokenizer": "keyword",
          "filter": [
            "name_gram_delimiter_start_inserter",
            "name_gram_delimiter_inserter",
            "name_gram_prefix_delimiter_processor",
            "code_preprocess_gram",
            "name_gram_delimiter_exclusion",
            "unique",
            "name_gram_delimiter_remover",
            "name_gram_length_exclusion",
            "lowercase",
            "unique",
            "name_ngrams",
            "prefix_min_length_remover",
            "name_gram_length_exclusion",
            "asciifolding",
            "unique"
          ],
          "type": "custom"
        },
        "full_name": {
          "tokenizer": "keyword",
          "filter": [
            "leading_dot_inserter",
            "code_preprocess_gram",
            "leading_dot_full_name_only_exclusion",
            "name_gram_length_exclusion",
            "lowercase",
            "asciifolding",
            "unique"
          ],
          "type": "custom"
        },
        "lowercase_keyword": {
          "tokenizer": "keyword",
          "filter": [
            "lowercase"
          ],
          "type": "custom"
        },
        "encoded_full_text": {
          "tokenizer": "standard",
          "filter": [
            "standard",
            "lowercase"
          ],
          "char_filter": [
            "punctuation_to_space_replacement",
            "remove_line_encoding"
          ],
          "type": "custom"
        }
      },
      "char_filter": {
        "punctuation_to_space_replacement": {
          "pattern": "[$^+=`~<>!\"#%&'()*,-./:;?@\\[\\]\\\\_{}]",
          "replacement": " ",
          "type": "pattern_replace"
        },
        "remove_line_encoding": {
          "pattern": "\u0011\\d+\u0012",
          "replacement": "",
          "type": "pattern_replace"
        }
      },
      "filter": {
        "name_gram_delimiter_start_inserter": {
          "pattern": "^(.*)",
          "replacement": "@\\^$1^",
          "type": "pattern_replace"
        },
        "name_gram_delimiter_inserter": {
          "pattern": "(?:(?<leading>\\p{Lu})(?<trailing>\\p{Ll}))",
          "replacement": "@${leading}${trailing}",
          "type": "pattern_replace"
        },
        "name_gram_prefix_delimiter_processor": {
          "pattern": "@\\^@",
          "replacement": "@\\^",
          "type": "pattern_replace"
        },
        "code_preprocess_gram": {
          "min_gram": 2,
          "max_gram": 70,
          "side": "back",
          "type": "edge_ngram"
        },
        "name_ngrams": {
          "min_gram": 2,
          "max_gram": 70,
          "type": "edge_ngram"
        },
        "name_gram_delimiter_exclusion": {
          "pattern": "((^[^@]*$)|(^[^@].*$)|(^[^\\<]*\\>$)|(^\\^..$))",
          "replacement": "",
          "type": "pattern_replace"
        },
        "name_gram_delimiter_remover": {
          "pattern": "\\@",
          "replacement": "",
          "type": "pattern_replace"
        },
        "leading_dot_full_name_only_exclusion": {
          "pattern": "^(?<empty>)(([^\\.].*)|(\\.(?<value>.*)))$",
          "replacement": "${empty}${value}",
          "type": "pattern_replace"
        },
        "leading_dot_inserter": {
          "pattern": "^.*$",
          "replacement": ".$0",
          "type": "pattern_replace"
        },
        "prefix_min_length_remover": {
          "pattern": "(^\\^..$)",
          "replacement": "",
          "type": "pattern_replace"
        },
        "camel_case_filter": {
          "patterns": [
            "(\\p{Lu}\\p{Lu}\\p{Lu}+)",
            "(\\p{Lu}\\p{Ll}\\w+)",
            "[^\\p{L}\\d]+(\\w+)",
            "[\\p{L}\\d]([^\\p{L}\\d]+\\w+)",
            "(\\d\\d+)"
          ],
          "preserve_original": true,
          "type": "pattern_capture"
        },
        "name_gram_length_exclusion": {
          "min": 2,
          "type": "length"
        }
      },
      "normalizer": {
        "lowercase_keyword_norm": {
          "filter": [
            "lowercase",
            "asciifolding"
          ],
          "type": "custom"
        }
      }
    }
  },
  "mappings": {
    "sources": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "uid": {
          "fields": {
            "keyword": {
              "ignore_above": 256,
              "type": "keyword"
            }
          },
          "type": "text"
        },
        "mergeId": {
          "type": "keyword"
        },
        "excludeFromSearch": {
          "type": "boolean"
        },
        "repoId": {
          "type": "keyword",
          "norms": false
        },
        "webAddress": {
          "type": "keyword",
          "doc_values": false,
          "index": false,
          "norms": false
        },
        "projectId": {
          "type": "keyword",
          "norms": false
        },
        "path": {
          "type": "keyword",
          "doc_values": false,
          "norms": false
        },
        "repoRelativePath": {
          "type": "keyword",
          "doc_values": false,
          "norms": false
        },
        "language": {
          "type": "keyword",
          "norms": false
        },
        "content": {
          "type": "text",
          "analyzer": "encoded_full_text",
          "index_options": "offsets",
          "term_vector": "with_positions_offsets"
        },
        "references": {
          "type": "object",
          "enabled": false,
          "properties": {
            "sharedValues": {
              "properties": {
                "referenceKind": {
                  "type": "keyword",
                  "norms": false
                },
                "projectId": {
                  "type": "text",
                  "analyzer": "lowercase_keyword",
                  "index_options": "docs",
                  "norms": false
                },
                "id": {
                  "type": "keyword"
                },
                "kind": {
                  "type": "text",
                  "analyzer": "lowercase_keyword",
                  "index_options": "docs",
                  "norms": false
                },
                "excludeFromDefaultSearch": {
                  "type": "boolean",
                  "null_value": false
                },
                "excludeFromSearch": {
                  "type": "boolean",
                  "null_value": false
                },
                "isImplicitlyDeclared": {
                  "type": "boolean",
                  "doc_values": false
                }
              },
              "type": "object"
            },
            "segments": {
              "properties": {
                "optimized": {
                  "type": "boolean"
                },
                "fullLength": {
                  "type": "integer"
                },
                "startsExpanded": {
                  "type": "boolean"
                },
                "starts": {
                  "properties": {
                    "valueByteWidth": {
                      "type": "integer"
                    },
                    "minValue": {
                      "type": "integer"
                    },
                    "decompressedLength": {
                      "type": "integer"
                    },
                    "compressedLength": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "binary"
                    },
                    "cdata": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    }
                  },
                  "type": "object"
                },
                "lengths": {
                  "properties": {
                    "valueByteWidth": {
                      "type": "integer"
                    },
                    "minValue": {
                      "type": "integer"
                    },
                    "decompressedLength": {
                      "type": "integer"
                    },
                    "compressedLength": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "binary"
                    },
                    "cdata": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    }
                  },
                  "type": "object"
                },
                "sharedIndices": {
                  "properties": {
                    "valueByteWidth": {
                      "type": "integer"
                    },
                    "minValue": {
                      "type": "integer"
                    },
                    "decompressedLength": {
                      "type": "integer"
                    },
                    "compressedLength": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "binary"
                    },
                    "cdata": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            },
            "count": {
              "type": "integer"
            },
            "item": {
              "properties": {
                "reference": {
                  "properties": {
                    "referenceKind": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    },
                    "projectId": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    },
                    "id": {
                      "properties": {},
                      "type": "object"
                    },
                    "kind": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    },
                    "excludeFromDefaultSearch": {
                      "type": "boolean"
                    },
                    "excludeFromSearch": {
                      "type": "boolean"
                    },
                    "isImplicitlyDeclared": {
                      "type": "boolean"
                    },
                    "extData": {
                      "properties": {},
                      "type": "object"
                    }
                  },
                  "type": "object"
                },
                "relatedDefinition": {
                  "properties": {},
                  "type": "object"
                },
                "lineNumber": {
                  "type": "integer"
                },
                "lineSpanStart": {
                  "type": "integer"
                },
                "lineSpanEnd": {
                  "type": "integer"
                },
                "lineSpanText": {
                  "fields": {
                    "keyword": {
                      "ignore_above": 256,
                      "type": "keyword"
                    }
                  },
                  "type": "text"
                },
                "lineOffset": {
                  "type": "integer"
                },
                "start": {
                  "type": "integer"
                },
                "length": {
                  "type": "integer"
                },
                "end": {
                  "type": "integer"
                }
              },
              "type": "object"
            }
          }
        },
        "classifications": {
          "type": "object",
          "enabled": false,
          "properties": {
            "sharedValues": {
              "properties": {
                "name": {
                  "fields": {
                    "keyword": {
                      "ignore_above": 256,
                      "type": "keyword"
                    }
                  },
                  "type": "text"
                },
                "defaultClassificationColor": {
                  "type": "integer"
                }
              },
              "type": "object"
            },
            "segments": {
              "properties": {
                "localSymbolGroupIds": {
                  "properties": {
                    "valueByteWidth": {
                      "type": "integer"
                    },
                    "minValue": {
                      "type": "integer"
                    },
                    "decompressedLength": {
                      "type": "integer"
                    },
                    "compressedLength": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "binary"
                    },
                    "cdata": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    }
                  },
                  "type": "object"
                },
                "optimized": {
                  "type": "boolean"
                },
                "fullLength": {
                  "type": "integer"
                },
                "startsExpanded": {
                  "type": "boolean"
                },
                "starts": {
                  "properties": {
                    "valueByteWidth": {
                      "type": "integer"
                    },
                    "minValue": {
                      "type": "integer"
                    },
                    "decompressedLength": {
                      "type": "integer"
                    },
                    "compressedLength": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "binary"
                    },
                    "cdata": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    }
                  },
                  "type": "object"
                },
                "lengths": {
                  "properties": {
                    "valueByteWidth": {
                      "type": "integer"
                    },
                    "minValue": {
                      "type": "integer"
                    },
                    "decompressedLength": {
                      "type": "integer"
                    },
                    "compressedLength": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "binary"
                    },
                    "cdata": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    }
                  },
                  "type": "object"
                },
                "sharedIndices": {
                  "properties": {
                    "valueByteWidth": {
                      "type": "integer"
                    },
                    "minValue": {
                      "type": "integer"
                    },
                    "decompressedLength": {
                      "type": "integer"
                    },
                    "compressedLength": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "binary"
                    },
                    "cdata": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            },
            "count": {
              "type": "integer"
            },
            "item": {
              "properties": {
                "localGroupId": {
                  "type": "integer"
                },
                "classification": {
                  "fields": {
                    "keyword": {
                      "ignore_above": 256,
                      "type": "keyword"
                    }
                  },
                  "type": "text"
                },
                "defaultClassificationColor": {
                  "type": "integer"
                },
                "start": {
                  "type": "integer"
                },
                "length": {
                  "type": "integer"
                },
                "end": {
                  "type": "integer"
                }
              },
              "type": "object"
            }
          }
        }
      }
    },
    "props": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "key": {
          "type": "keyword",
          "index": true,
          "norms": false,
          "normalizer": "lowercase_keyword_norm"
        },
        "value": {
          "type": "keyword",
          "index": true,
          "norms": false,
          "normalizer": "lowercase_keyword_norm"
        },
        "objectId": {
          "type": "keyword"
        }
      }
    },
    "defs": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "uid": {
          "fields": {
            "keyword": {
              "ignore_above": 256,
              "type": "keyword"
            }
          },
          "type": "text"
        },
        "tags": {
          "type": "keyword",
          "norms": false
        },
        "isReferencedSymbol": {
          "type": "boolean"
        },
        "span": {
          "properties": {
            "definition": {
              "properties": {
                "comment": {
                  "type": "keyword",
                  "doc_values": false,
                  "index": false,
                  "norms": false
                },
                "typeName": {
                  "type": "keyword",
                  "doc_values": false,
                  "index": false,
                  "norms": false
                },
                "shortDisplayName": {
                  "type": "keyword",
                  "doc_values": false,
                  "index": false,
                  "norms": false
                },
                "displayName": {
                  "type": "keyword",
                  "doc_values": false,
                  "index": false,
                  "norms": false
                },
                "shortName": {
                  "type": "text",
                  "analyzer": "partial_name",
                  "index_options": "docs",
                  "norms": false
                },
                "QualifiedName": {
                  "type": "text",
                  "analyzer": "full_name",
                  "index_options": "docs",
                  "norms": false
                },
                "glyph": {
                  "type": "keyword",
                  "doc_values": false,
                  "index": false,
                  "norms": false
                },
                "symbolDepth": {
                  "type": "integer",
                  "doc_values": false
                },
                "uid": {
                  "type": "keyword",
                  "doc_values": false,
                  "index": false,
                  "norms": false
                },
                "projectId": {
                  "type": "text",
                  "analyzer": "lowercase_keyword",
                  "index_options": "docs",
                  "norms": false
                },
                "id": {
                  "type": "keyword"
                },
                "kind": {
                  "type": "text",
                  "analyzer": "lowercase_keyword",
                  "index_options": "docs",
                  "norms": false
                },
                "excludeFromDefaultSearch": {
                  "type": "boolean",
                  "null_value": false
                },
                "excludeFromSearch": {
                  "type": "boolean",
                  "null_value": false
                },
                "isImplicitlyDeclared": {
                  "type": "boolean",
                  "doc_values": false
                }
              },
              "type": "object"
            },
            "lineNumber": {
              "type": "integer",
              "doc_values": false
            },
            "lineSpanStart": {
              "type": "integer",
              "doc_values": false
            },
            "start": {
              "type": "integer"
            },
            "length": {
              "type": "integer"
            }
          },
          "type": "object"
        },
        "fileMergeId": {
          "type": "keyword",
          "doc_values": false,
          "index": false,
          "norms": false
        },
        "filePath": {
          "type": "keyword",
          "norms": false
        },
        "language": {
          "type": "keyword",
          "norms": false
        }
      }
    },
    "refs": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "projectId": {
          "type": "keyword",
          "norms": false
        },
        "reference": {
          "properties": {
            "referenceKind": {
              "type": "keyword",
              "norms": false
            },
            "projectId": {
              "type": "text",
              "analyzer": "lowercase_keyword",
              "index_options": "docs",
              "norms": false
            },
            "id": {
              "type": "keyword"
            },
            "kind": {
              "type": "text",
              "analyzer": "lowercase_keyword",
              "index_options": "docs",
              "norms": false
            },
            "excludeFromDefaultSearch": {
              "type": "boolean",
              "null_value": false
            },
            "excludeFromSearch": {
              "type": "boolean",
              "null_value": false
            },
            "isImplicitlyDeclared": {
              "type": "boolean",
              "doc_values": false
            }
          },
          "type": "object"
        },
        "relatedDefinitions": {
          "type": "keyword"
        },
        "symbolLineSpanList": {
          "type": "object",
          "enabled": false,
          "properties": {
            "sharedValues": {
              "properties": {
                "lineStart": {
                  "type": "integer"
                },
                "lineNumber": {
                  "type": "integer"
                },
                "lineSpanText": {
                  "type": "string",
                  "index": "no"
                }
              },
              "type": "object"
            },
            "segments": {
              "properties": {
                "optimized": {
                  "type": "boolean"
                },
                "fullLength": {
                  "type": "integer"
                },
                "startsExpanded": {
                  "type": "boolean"
                },
                "starts": {
                  "properties": {
                    "valueByteWidth": {
                      "type": "integer"
                    },
                    "minValue": {
                      "type": "integer"
                    },
                    "decompressedLength": {
                      "type": "integer"
                    },
                    "compressedLength": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "binary"
                    },
                    "cdata": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    }
                  },
                  "type": "object"
                },
                "lengths": {
                  "properties": {
                    "valueByteWidth": {
                      "type": "integer"
                    },
                    "minValue": {
                      "type": "integer"
                    },
                    "decompressedLength": {
                      "type": "integer"
                    },
                    "compressedLength": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "binary"
                    },
                    "cdata": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    }
                  },
                  "type": "object"
                },
                "sharedIndices": {
                  "properties": {
                    "valueByteWidth": {
                      "type": "integer"
                    },
                    "minValue": {
                      "type": "integer"
                    },
                    "decompressedLength": {
                      "type": "integer"
                    },
                    "compressedLength": {
                      "type": "integer"
                    },
                    "data": {
                      "type": "binary"
                    },
                    "cdata": {
                      "fields": {
                        "keyword": {
                          "ignore_above": 256,
                          "type": "keyword"
                        }
                      },
                      "type": "text"
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            },
            "count": {
              "type": "integer"
            },
            "item": {
              "properties": {
                "lineNumber": {
                  "type": "integer"
                },
                "lineSpanStart": {
                  "type": "integer"
                },
                "lineSpanEnd": {
                  "type": "integer"
                },
                "lineSpanText": {
                  "fields": {
                    "keyword": {
                      "ignore_above": 256,
                      "type": "keyword"
                    }
                  },
                  "type": "text"
                },
                "lineOffset": {
                  "type": "integer"
                },
                "start": {
                  "type": "integer"
                },
                "length": {
                  "type": "integer"
                },
                "end": {
                  "type": "integer"
                }
              },
              "type": "object"
            }
          }
        },
        "symbolLineSpans": {
          "type": "object",
          "enabled": false,
          "properties": {
            "lineSpanText": {
              "type": "string",
              "index": "no"
            },
            "lineNumber": {
              "type": "integer",
              "doc_values": false
            },
            "lineSpanStart": {
              "type": "integer",
              "doc_values": false
            },
            "start": {
              "type": "integer"
            },
            "length": {
              "type": "integer"
            }
          }
        },
        "fileMergeId": {
          "type": "keyword",
          "doc_values": false,
          "index": false,
          "norms": false
        },
        "filePath": {
          "type": "keyword",
          "norms": false
        },
        "language": {
          "type": "keyword",
          "norms": false
        }
      }
    },
    "projects": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "id": {
          "type": "keyword"
        },
        "repositoryName": {
          "type": "keyword"
        },
        "projectKind": {
          "type": "text",
          "analyzer": "lowercase_keyword",
          "index_options": "docs",
          "norms": false
        },
        "repoId": {
          "type": "keyword",
          "norms": false
        },
        "dateUploaded": {
          "type": "date"
        },
        "referencedProjects": {
          "type": "nested",
          "properties": {
            "projectId": {
              "type": "string",
              "index": "not_analyzed"
            },
            "definitions": {
              "type": "object",
              "properties": {
                "comment": {
                  "type": "keyword",
                  "doc_values": false,
                  "index": false,
                  "norms": false
                },
                "typeName": {
                  "type": "keyword",
                  "doc_values": false,
                  "index": false,
                  "norms": false
                },
                "shortDisplayName": {
                  "type": "keyword",
                  "doc_values": false,
                  "index": false,
                  "norms": false
                },
                "displayName": {
                  "type": "keyword",
                  "doc_values": false,
                  "index": false,
                  "norms": false
                },
                "shortName": {
                  "type": "text",
                  "analyzer": "partial_name",
                  "index_options": "docs",
                  "norms": false
                },
                "QualifiedName": {
                  "type": "text",
                  "analyzer": "full_name",
                  "index_options": "docs",
                  "norms": false
                },
                "glyph": {
                  "type": "keyword",
                  "doc_values": false,
                  "index": false,
                  "norms": false
                },
                "symbolDepth": {
                  "type": "integer",
                  "doc_values": false
                },
                "uid": {
                  "type": "keyword",
                  "doc_values": false,
                  "index": false,
                  "norms": false
                },
                "projectId": {
                  "type": "text",
                  "analyzer": "lowercase_keyword",
                  "index_options": "docs",
                  "norms": false
                },
                "id": {
                  "type": "keyword"
                },
                "kind": {
                  "type": "text",
                  "analyzer": "lowercase_keyword",
                  "index_options": "docs",
                  "norms": false
                },
                "excludeFromDefaultSearch": {
                  "type": "boolean",
                  "null_value": false
                },
                "excludeFromSearch": {
                  "type": "boolean",
                  "null_value": false
                },
                "isImplicitlyDeclared": {
                  "type": "boolean",
                  "doc_values": false
                }
              }
            }
          }
        },
        "webAddress": {
          "type": "keyword",
          "doc_values": false,
          "index": false,
          "norms": false
        }
      }
    },
    "repos": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "id": {
          "type": "keyword"
        },
        "webAddress": {
          "type": "keyword",
          "doc_values": false,
          "index": false,
          "norms": false
        },
        "sourceControlLocation": {
          "type": "keyword"
        },
        "branchName": {
          "type": "keyword"
        },
        "dateUploaded": {
          "type": "date"
        },
        "dateCommitted": {
          "type": "date"
        },
        "commitId": {
          "type": "keyword"
        },
        "version": {
          "type": "keyword",
          "norms": false
        },
        "name": {
          "type": "keyword"
        },
        "sourcesIndexName": {
          "type": "keyword"
        }
      }
    }
  }
}
# Response:
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "No handler for type [string] declared on field [projectId]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "Failed to parse mapping [projects]: No handler for type [string] declared on field [projectId]",
    "caused_by" : {
      "type" : "mapper_parsing_exception",
      "reason" : "No handler for type [string] declared on field [projectId]"
    }
  },
  "status" : 400
}
```

**Comment by ljcollins25** [comment] 2018-04-18 17:31
This is almost certainly caused by breaking changes in ElasticSearch. The readme is pointing to the current version 6.x. The Codex from master branch is targeted at ElasticSearch 5.5.1. I've updated the readme with the correct link (189b075bb5b2212c09c877a2af5d5fe0a78b28a2). Closing the issue. If this does not resolve the issue for you, I will investigate further.

**Closed by ljcollins25** 2018-04-18 17:31 UTC

**Comment by DustinCampbell** [comment] 2018-04-18 19:49
Thanks @ljcollins25 -- I'll give it a try.

**Comment by DustinCampbell** [comment] 2018-04-18 20:47
I verified that using the `Microsoft.Build.Locator` package makes Codex work with the latest VS 2017.

I filed issue #102 and submitted pull request #103 to fix it. :smile:
